### ISSUE TITLE
Add null-safety support

### ISSUE THREAD

**Issue by harsimranmaan** [rydmike/flex_color_scheme#1]
First of all, thanks a lot for this package. It saved me so much time as theming and frontend isn't really my forte.

I have been in the process of migrating my app to dart 2.12.x-pre to get some basic null safety checks going. It would be nice if this package had a null safe version too. See https://dart.dev/null-safety/migration-guide

Null safety is not on my critical path but would likely be at some point when a stable flutter version with null safety is released.

Happy new year 🎉

**Comment by harsimranmaan** [comment]
I'll be happy to help here if needed

**Comment by rydmike** [comment]
@harsimranmaan I noticed your usage of FlexColorScheme in https://github.com/bigpanther/shipanther/pull/215#event-4160609370 and yes I also saw in your implementation that you were building your app with a null safe version of Flutter.

Thanks for the tag and credits in the case. Happy to hear that FlexColorScheme found some real world usage already this early after its release. Glad if it helped. 

Yes theming can indeed be a bit of time waster, which is why I put together this package as I found myself applying a lot of the theme fixes and things I included in FlexColorScheme for every app. For Flexfold I also made just for demo purposes a bunch of imo nice ready made color schemes, so I thought maybe it could be helpful too and add them as well to the package. Actually FlexColorScheme was first just an experiment in the Flexfold demo app when I was trying to see if I could come up with a solution that makes theming easier and nicer to manage multiple themes. I also got a some questions about how I managed all the theming in Flexfold, so the idea for this package was originally born there to make a package out of it, and show how it was done. The Flexfold demo app was kind of my test bed for converting FlexColorScheme to a package. Example 5 in the package source is pretty close to how theming is done in the Flexfold demo app now when Flexfold also uses the package.

---

**To the actual topic** about null safety, yes it is **definitely** on my to do list to make null-safe version in order to be ready for it before it reaches stable. It is mentioned as well in the todo list at the end of the package **Changelog** page: https://pub.dev/packages/flex_color_scheme/changelog.

I was planning to add some reasonable test coverage to the package before I do the migration and then release a null safe version, but I could make it the other way around as well if you are in hurry. But null-safety is definitely coming. 

In my projects I work mostly on the dev channel for Windows build support, so I'm reasonably familiar with it, since it has been available there and on master too for a while. I was planning to use the migration of this package and the [FlexColorPicker](https://pub.dev/packages/flex_color_picker/changelog) to null safety to get fully up to speed and start using it in my own none public projects as well.

---

Thanks for opening this issue, I now have good motivation to get it done so I can close it! 😃

**Comment by rydmike** [comment]
@harsimranmaan 
For your info, a first version of FlexColorScheme that uses null safety has been released.

https://pub.dev/packages/flex_color_scheme/versions/2.0.0-nullsafety.1 

FlexColorScheme only depends on Flutter SDK so the null safety is sound already now.

Since this is the first null safe release, please open issues if you come across any oddities or issues.

Tests pass (null related tests removed), code coverage is >99.5% and the five bundled example apps also build and work the way they should with sound null safety. 

I just also made a GitHub pre-release of it as well, this then kicks off the GitHub Actions CI/CD that runs Analyze+tests+makes codecov report+builds all Web examples + Deploy all Web examples to GitHub Pages.

It is still building them and will soon also deploy new live versions of the Web examples of the bundled demos, so they should soon all also be builds from the null-safe version.... waiting... takes about 10min for GitHub to do the builds and publishing of them, on GitHub Pages... and there... the demos built with the null-safe version are live and running fine on Web too.
 
Closing this issue. 😄

**Comment by harsimranmaan** [comment]
Thanks @rydmike. I'll give it a go

**Comment by ErliSoares** [comment]
Any news about the stable version for null safety?

**Comment by rydmike** [comment]
@ErliSoares @harsimranmaan FYI - 2.0.0 stable with sound null-safety is available now.
