### ISSUE TITLE
Google fonts issue

### ISSUE THREAD

**Issue by DarkHeros09** [rydmike/flex_color_scheme#103]
Hi

First of all thank you for making this great package, I'm really loving it.
Today i discovered this weird issue regarding fonts styling more specifically spacing.
I've enabled the grid so it can be more obvious.

1. when using the Google fonts inside the Text widget

```dart
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

class TestText extends StatelessWidget {
  const TestText({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Text(
          'Test Text',
          style: GoogleFonts.roboto(
            fontSize: 16,
            fontWeight: FontWeight.w700,
          ),
        ),
      ),
    );
  }
}
```
The result:
![normal](https://user-images.githubusercontent.com/39935182/206804549-e33c84db-7fe8-49a2-b30d-5bbeff331581.jpg)
_______

2. when using Google fonts inside the FlexColorScheme

- test.dart

```dart
import 'package:flutter/material.dart';

class TestText extends StatelessWidget {
  const TestText({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Text(
          'Test Text',
          style: Theme.of(context).textTheme.subtitle2,
        ),
      ),
    );
  }
}
```

- theme.dart
```dart
import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

FlexColorScheme myFlexColorScheme = FlexColorScheme(
  fontFamily: GoogleFonts.roboto().fontFamily,
  textTheme: const TextTheme(
    subtitle2: TextStyle(fontSize: 16, fontWeight: FontWeight.w700),
  ),
);
```

- main.dart
```dart
theme: myFlexColorScheme.toTheme,
```

The result:
![weird](https://user-images.githubusercontent.com/39935182/206805305-8fab9f8f-19a8-41d7-8899-b186cf6e05d8.jpg)

Its more obvious when writing in Arabic using NotoKufiArabic font.

- Normal
![normal_arabic](https://user-images.githubusercontent.com/39935182/206806144-513495b8-b944-42c3-906c-ee69b0c86517.jpg)

- Weird behavior
![weird_arabic](https://user-images.githubusercontent.com/39935182/206806195-675b2c96-457f-4b50-8db7-e8d1d2ba5db8.jpg)

Thank you for your time.

**Comment by DarkHeros09** [comment]
after more experiment with theme data, and loading fonts from local assets. it turns out it's google font package's issue not flex_color_scheme.

sorry for bothering.

**Comment by rydmike** [comment]
Hi @DarkHeros09, still thanks for filing the issue and concern though. Sorry it took me a bit of time to respond. Glad if you found the issue already. 

To be honest I'm having a hard time seeing a huge difference in screenshots (I would need to extract them and make one semi transparent an overlay them I guess). I do see a slight difference in the horiszntal offset/spacing. Is that what I supposed to notice? This is perhaps caused by the different used letter spacing in different Typography used by the ThemeData in the issue demo.

When reading this on my phone the other day, before you closed it, I was going to suggest that one potential source of difference could be the used Typography.

A default `ThemeData` uses `Typography.material2014`, this is old and should really not be used anymore, but Flutter still defaults to it. So if your example without FlexColorScheme just use default ThemeData, with no Typography specified, then that application/issue demo is using `Typography.material2014`.

Whereas FlexColorScheme uses `Typography.material2018` by default, like any app using Material2 should do based on Material2 guide.

When you opt-in on Material3, FlexColorScheme, like Flutter, uses `Typography.material2021`, which I really recommend for all apps, regardless of if Material2 or 3 is used, since it is much nicer than any of the older ones.

The difference in typography will affect things like letter spacing, in addition to many font sizes. There are a lot of letterSpacing differences between 2014 and 2018 typography, that would cause the letters to align slightly differently on the grid. This is why I suspected it might be the cause of the observed differences. However, if you already found some other cause, I'll take that as the cause too :)

If you did have different Typography at play in the issue example above (hard for me to say since the code samples are inconclusive/incomplete on the matter), but if you did, then in your `ThemeData` that does not use FlexColorScheme, try specifying typography as:

```dart
typography: Typography.material2018(platform: defaultTargetPlatform),
```

Did it change the result?

Alternatively you can also use older and uglier 2104 Typography in `FlexColorScheme` with:

```dart
typography: Typography.material2014(platform: defaultTargetPlatform),
```

At the end of the day, FlexColorScheme only returns a `ThemeData` object, so it cannot do anything to the Theme that you cannot also specify with a very long and elaborate `ThemeData` object.


Anyway, this was just some additional thoughts and input on this issue, just in case 😄
