### ISSUE TITLE
`FlexSubThemesData` doesn't respect border absence on `InputDecoration.collapsed`

### ISSUE THREAD

**Issue by hamishjohnson** [rydmike/flex_color_scheme#110]
Hiya, love the package and your explanations with Majid Hajian

For an Input with `InputDecoration.collapsed`, with M2 & M3 there is no border.

But using `FlexSubThemesData`, it's not possible to have no borders on Inputs

The closest I can get is 

```
const subThemesData = FlexSubThemesData(
  inputDecoratorBorderType: FlexInputBorderType.underline,
  inputDecoratorFocusedBorderWidth: 0,
  inputDecoratorUnfocusedHasBorder: false,
);
```

Which results in this:
<img width="167" alt="Screenshot 2023-01-14 at 17 01 22" src="https://user-images.githubusercontent.com/9589803/212466593-3cdc79c1-0fff-4f32-a254-f4bee2140d55.png">

Even when setting
```
InputDecoration.collapsed(
                      hintText: '',
                      border: InputBorder.none,
                    ),
```

The Input still has that border

**Comment by rydmike** [comment]
Hi @hamishjohnson, thanks for the issue report.

It is a correct observation, to not have any border when an input is focused is something the current does not includ.

Also changing border width to 0 does not help because of how the Flutter framework handles border width 0, which actually draws a border with physical pixel 1, when you set it to 0.

https://github.com/flutter/flutter/blob/68dd63d66ba6359b377a48c3bb4b028ab5ef5140/packages/flutter/lib/src/painting/borders.dart#L116

Funky right :)

For the unfocused border case it is handled as separate case to just not included any border in theme when the flag is set. But alas there is no, `noFocusedBorder` flag or case.

Your timing is actually very good since I am in the process of adding better M3 support and more features for FCS to the `InputDecoratorTheme`. I had not actually thought about this particular theming use-case, but it makes perfect sense to add it as well.

In FlexColorScheme docs I mention that its intention is not to offer **everything** you can do with `ThemeData` and its component sub-themes. The intent is to make common use cases quicker and easier to configure, and on the color themes side to also do things the framework simply cannot do out of the box.

That being said, configuring the `InputDecorationTheme` is silly complex and tedious and including this makes sense while anyway reworking it.

Meanwhile, if you urgently need themed support for this, you can always amend and modify the `ThemeData` that FlexColorScheme outputs to do it already now using `copyWith` on the `ThemeData` and the `InputDecorationTheme` it produces.

If you are not familiar with this, there are a few related examples in the discussion, for example this one https://github.com/rydmike/flex_color_scheme/discussions/92

In any case, thanks bringing up this feature gap and need. I plan to land support for this in next feature release that will be out shortly after Flutter Forward on Jan 25th. Might be a few days later since I will actually be physically at the event in Nairobi 😄

**Comment by hamishjohnson** [comment]
Ok, thanks!

I think there might be something I misunderstand about this package, or the flutter sdk. It just creates a more customised ThemeData at the end of the day, right?

But then it confuses me why a `border: InputBorder.none` on the `InputDecoration` doesn't work. Is that just part of the flutter sdk, that if `InputDecorationTheme` has a border, `InputBorder.none` no longer works?

**Comment by rydmike** [comment]
There is a separate input border property for every state (enabled, focused, hover, error, focusedError, disabled) in InputDecoration, and the theme uses them all, it does not even use border at all if I recall correctly. To get rid of it, and override what the theme has defined you need to set InputBorder.none on all of them on widget level.

The InputDecorator has a bit mixed bag legacy API. It uses MaterialState property for newer parts, but older parts still sport the old style with a property per state.

I actually tried to get it to work by using only border and MaterialState, in the theme in my new wip version, it should work, but it did not work correctly. So I had to revert and still use all the individual properties. I made a note to revisit it later and make an issue report of it, if I can repeat and demonstrate the problem in isolation.

TextField and InputDecoration is quite involved and tricky. The Flutter code behind them is quite fascinating and really deep rabbit holes to study 😀

**Comment by rydmike** [comment]
Still same milestone target, but the release will be called 7.0.0, since I am introducing a few minor default style breaking changes. There are no breaking API changes though. There is a beta of it available on pub if you are feeling experimental, it includes this new property. 
https://pub.dev/packages/flex_color_scheme/versions/7.0.0-dev.2

**Comment by rydmike** [comment]
Final beta of version 7 is out. There will be no additional features or API changes in the stable release. More info in this tweet thread: 

https://twitter.com/RydMike/status/1637228788139302914?s=20

Feel free to try it. 

Closing this feature request as delivered in version7 final beta. Well to the degree it can be supported by current `InputDecorator` theme in Flutter anyway.
