### ISSUE TITLE
CircleAvatar Widget is ignored by colorscheme

### ISSUE THREAD

**Issue by florianh01** [rydmike/flex_color_scheme#14]
Hi, thank you for this great package.

I'm not quite sure if this is the intended behavior, but I noticed that the default CircleAvatar() Widget's background color has the standard blue color and is ignored by the colorScheme. 

From the Circle Avatar Documentation:
> If a [backgroundColor] is not specified, the theme's [ThemeData.primaryColorLight] is used with dark foreground colors, and [ThemeData.primaryColorDark] with light foreground colors.

I think it would be great to change the background color of CircleAvatar() to colorScheme.surface or something else for further improvements of the package.

**Comment by rydmike** [comment]
Hi @florianh01 thanks for your report. I had a look at it and I am unable to to reproduce the issue.

If you look eg at example 5 here https://rydmike.com/flexcolorscheme5/#/
And the Theme Showecase there, the `CircleAvatar` included there has a background that changes with the theme.

And it follows exactly the above default Flutter Circle Avatar documentated behavior.

## Two examples:

### Barossa Theme:
![image](https://user-images.githubusercontent.com/39990307/129404200-39932a68-e706-453f-9f00-4db4d456c655.png)


![image](https://user-images.githubusercontent.com/39990307/129404257-7046b101-6dc3-4e93-9427-897d27153e8b.png)

### Pink Sakura theme example:
![image](https://user-images.githubusercontent.com/39990307/129404504-eaa154a1-29c1-4c28-83b7-c16cdb7c7930.png)

![image](https://user-images.githubusercontent.com/39990307/129404334-d570d58d-aa89-4ce8-b0c7-ba0b5876af9f.png)



## More info on the topic 

FlexColorScheme is able to do this correctly because it also computes suitable colors for the `ThemeData.primaryColorLight` and `ThemeData.primaryColorDark` automatically when you create the `ThemeData` with `FlexColorScheem.toTheme` that matches the `ThemeData.colorScheme.primary` color that it also sets, but as lighter and darker hues of it.

When you create `ThemeData` with Flutter's `ThemeData.from(colorScheme)`, those properties are not automatically given any values that match the `colorScheme`. You will have to define them manually yourself and apply them with `ThemeData.copyWith`. Otherwise it gets default blue hue colors, even if your `ThemeData.from(colorScheme)` might have specified some other primary color than blue.

You can in fact with example 5 simulate this issue with Flutter's default colorscheme based ThemeData constructor, by turning off this switch:

![image](https://user-images.githubusercontent.com/39990307/129406953-c7c9c95d-b319-4372-92e1-7aefaa0e3d1a.png)

Above you can see that the CircleAvatar gets a blue color that is not at all part of the selected and active color scheme. This is the way Flutter normally works when using its recommended `ThemeData.from(colorScheme)` theming factory. This is actually one of the issues with it, that **FlexColorScheme** was designed to specifically address.

As another intresting side note, if you use the older Flutter plain `ThemeData` factory constructor you will get `ThemeData` with `primaryColorLight` and `primaryColorDark` that follows the primary colorswatch that the `ThemeData` factory constructor uses. However, that older constructor has some other theming issues and a much less nice dark theme.

## Why are you seeing this issue?

This I cannot answer without actually seeing code that reproduces the issue, or perhaps with some more explanations on how you have setup your theme.

If you have some code that you can share, or can make a reproduction case, I would be happy to take a look at it and see if I can figure out why you are seeing the result that you are.

**Comment by rydmike** [comment]
As an additional note, you should **NOT** theme your application by getting the the color scheme for `FlexColorScheme.toShceme` that just returns the `ColorScheme` defined by **FlexColorScheme** and then use that as input to e.g. `ThemeData.from`, because this will result in a blue `CircleAvatar` just as any other `ThemeData.from` will do. 

A Flutter `ColorScheme` does not contain color values that are guaranteed to be correct and usable for `ThemeData.primaryColorLight` and `ThemeData.primaryColorDark`. Currently the SDK just ignores the fact that some Widgets actually uses and needs these definitions to get a theme that matches the used color scheme. I have reported this issue as bug ages, but it has been happily ignored, there is a grander migration scheme going on where eventually I suspect the ThemeData color properties `primaryColorLight` and `primaryColorDark` will be depracted and no standard Widgets will use them anymore, instead they will probably compute needed shades of colors defined in `ThemeData.colorScheme`.

The **FlexColorScheme** documentation specifically mentions that the above way is **NOT** the way to use FlexColorScheme to theme your application. You should use its `toTheme()` method, it takes care of also defining the above correct `primaryColorLight` and `primaryColorDark` colors, plus a number of other nice and convenient default theming.

The `toScheme()` method only exist so that you can retrieve the color scheme of the created theme, in order to use this `ColorScheme` and its colors when creating some more advanced and further customized sub-themes. Plus I wanted to use it to the be able to test and demonstrate the unnuanced but important differences that FlexColorScheme can fix, which that mentioned switch above shows in example 5.

**Comment by florianh01** [comment]
Hi @rydmike,

Thanks for this detailed answer. You're right, the fault here is one hundred percent mine. 🤦‍♂️

This was my code:

```
ThemeData.from (
           colorScheme: FlexColorScheme.light (
                   colors: customFlexScheme.light,
                   appBarElevation: 4.0,
                   surface: const Color (0xffffffff),
                   onPrimary: const Color (0xffffffff),
                   onSecondary: const Color (0xff000000),
                   onBackground: const Color (0xff000000),
                   onSurface: const Color (0xff000000),
                   onError: const Color (0xffffffff),
                   transparentStatusBar: true,
                   swapColors: false)
               .toScheme,
),
```

I will now change this in your recommended way. Thank you!

Themeing in Flutter is really bad, but with your package it's really a no-brainer. Thank you!

**Comment by florianh01** [comment]
@rydmike 
Sorry that I have to annoy you again. I still have a question about TextTheme. Since FlexColorScheme() has no parameter for the TextTheme, I used copyWith(). Is that the recommended way?

```
theme: FlexColorScheme.light(
          colors: customFlexScheme.light,
          appBarElevation: 4.0,
          surface: const Color(0xffffffff),
          onPrimary: const Color(0xffffffff),
          onSecondary: const Color(0xff000000),
          onBackground: const Color(0xff000000),
          onSurface: const Color(0xff000000),
          onError: const Color(0xffffffff),
        ).toTheme.copyWith(
              textTheme: const TextTheme(
                headline6: TextStyle(
                  fontSize: 20.0,
                  fontWeight: FontWeight.w500,
                  letterSpacing: 0.15,
                  height: 24 / 20,
                  color: Color(0xff6200EE),
                ),
// ...
),
)
```

**Comment by rydmike** [comment]
Hi @florianh01,

No problem at all.

Yes you can indeed crate a copy of the the produced `ThemeData` you get from `FlexColorScheme.toTheme` with `copyWith`, it is just a standard `ThemeData` object, so anything you can do anything to it, that you can to any `ThemeData` object.

You are right that the `TextTheme` is not directly exposed, so using `copyWith` is the way to "modifying" it by creating a copy with the desired modifications included. You can if you like use `fontFamily` to with GoolgeFonts change the overall default font already in FlexColorSceheme's constructors.

But yes maybe I should expose `textTheme` in a later version, but since you can already customize do it with `copyWith` I did not feel it was necessary.

By the way, an I am just curious, but why are you setting all the `on`Colors in your `FlexColorScheme.light` factory constructor? 

Unless you really want to make something really custom, you do not have to do that. From the looks of it, it seems you are just using standard surface and and onColors, so you don't have to define them. The raw default constructor does indeed need them since it does not know if you are making a light or dark theme, but the `FlexColorScheme.light` and `FlexColorScheme.dark` factories knows what surface, background and onColors and error colors should be for their light and dark mode themes by default. They are just exposed in case you really do want to customize them.

I added a simple demo repo https://github.com/rydmike/fcs_simple_demo that is easy to use if you want to just in code experiment with custom themes based on **FlexColorScheme**, instead of interactively like example 5 allows you to do.

It's main file looks like below. It includes placeholder for options you might want to experiment with, and also an example using GoogleFonts to set another default font.

I think I will in the docs in later add a link to this repo as another simple example that allows you the get started with experimenting FlexColorScheme themes and options in code, instead of the more complicated interactive run time theming demos.

```dart
void main() => runApp(const DemoApp());

// For our custom scheme we will define primary and secondary colors, but no
// variant or other colors.
final FlexSchemeColor _mySchemeLight = FlexSchemeColor.from(
  primary: const Color(0xFF3B5997),
  // If you do not want to define secondary, primaryVariant and
  // secondaryVariant, error and appBar colors you do not have to,
  // they will get defined automatically.
  //
  // Here we do define a secondary color, but if you don't it will get a
  // default shade based on the primary color.
  secondary: const Color(0xFFFB8123),
);

// This is custom defined matching dark mode colors, but below we also show
// how to base it of the light color scheme instead as well.
final FlexSchemeColor _mySchemeDark = FlexSchemeColor.from(
  primary: const Color(0xFF8B9DC3),
  secondary: const Color(0xFFFCB075),
);

class DemoApp extends StatelessWidget {
  const DemoApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'FlexColorScheme',
      // Define the light theme for the app, based on defined colors.
      theme: FlexColorScheme.light(
        colors: _mySchemeLight,
        // Just want to use a built in scheme? Then comment colors above and
        // use scheme below to select a built-in one:
        // scheme: FlexScheme.hippieBlue,
        surfaceStyle: FlexSurface.medium,
        appBarStyle: FlexAppBarStyle.primary,
        appBarElevation: 0,
        transparentStatusBar: true,
        tabBarStyle: FlexTabBarStyle.forAppBar,
        tooltipsMatchBackground: false,
        swapColors: false,
        visualDensity: FlexColorScheme.comfortablePlatformDensity,
        // Set the default font for the ThemeData using GoogleFonts.
        fontFamily: GoogleFonts.lato().fontFamily,
      ).toTheme,
      // Define the dark theme for the app, based on custom colors.
      darkTheme: FlexColorScheme.dark(
        // If you want to base the dark scheme on your light colors, this is
        // a nice shortcut if you do not want to design your dark theme.
        // The whiteBlend for the desaturation of the light theme colors
        // defaults to 35%, you can try other values too, here eg 30.
        colors: _mySchemeLight.toDark(30),
        // If you want to use the defined custom dark colors, use it instead:
        // colors: _mySchemeDark,
        // Just want to use a built in scheme? Then comment colors above and
        // use scheme below to select a built-in one:
        // scheme: FlexScheme.hippieBlue,
        surfaceStyle: FlexSurface.strong,
        appBarStyle: FlexAppBarStyle.background,
        appBarElevation: 0,
        transparentStatusBar: true,
        tabBarStyle: FlexTabBarStyle.forAppBar,
        tooltipsMatchBackground: false,
        swapColors: false,
        darkIsTrueBlack: false,
        visualDensity: FlexColorScheme.comfortablePlatformDensity,
        fontFamily: GoogleFonts.lato().fontFamily,
      ).toTheme,
      // Use the above dark or light theme based on active themeMode below.
      // Toggle in code here, or set to system to toggle with device.
      themeMode: ThemeMode.system,
      home: const HomePage(),
    );
  }
}
```

**Comment by florianh01** [comment]
> By the way, an I am just curious, but why are you setting all the `on`Colors in your `FlexColorScheme.light` factory constructor?

This has no further meaning, I just created a custom material design theme again to play around with your package.
I used the colors from this page https://material.io/design/color/the-color-system.html, actually there is no difference to the material design theme of your package. - It's just to play around :)

Unfortunately I still have a problem with my theme.

It works fine in dark mode, but in light mode all text appears in white. (It doesn't matter whether I have defined the on-colors or not). As a result, the text is illegible.

The text should automatically appear as black, shouldn't it?

Here is my code:

```
theme: FlexColorScheme.light(
          scheme: FlexScheme.aquaBlue,
          //colors: customFlexScheme.light,
          appBarElevation: 4.0,
        ).toTheme.copyWith(
              textTheme: const TextTheme(

                headline6: TextStyle(
                  fontSize: 20.0,
                  fontWeight: FontWeight.w500,
                  letterSpacing: 0.15,
                  height: 24 / 20,
                ),

                headline5: TextStyle(
                  fontSize: 24.0,
                  fontWeight: FontWeight.w500,
                  letterSpacing: 0.15,
                ),

                headline4: TextStyle(
                  fontSize: 18.0,
                  fontWeight: FontWeight.w600,
                  letterSpacing: 0.15,
                ),

                subtitle2: TextStyle(
                  fontSize: 17.0,
                  fontWeight: FontWeight.w500,
                  letterSpacing: 0.25,
                  height: 20 / 17,
                ),

                bodyText1: TextStyle(
                  fontSize: 14.0,
                  fontWeight: FontWeight.w400,
                  letterSpacing: 0.25,
                  height: 20 / 14.0,
                ),
              ),
            ),
```
As a solution, I could of course set every TextTheme to black, but the default TextThemes would still appear in white (for example with ListTiles ...)

When I use the unrecommended way, the textColors appear as expected. 
```
theme: ThemeData.from(
          colorScheme: FlexColorScheme.light(
                  colors: customFlexScheme.light,
                  appBarElevation: 4.0,)
              .toScheme,
          textTheme: const TextTheme(

            headline6: TextStyle(
              fontSize: 20.0,
              fontWeight: FontWeight.w500,
              letterSpacing: 0.15,
              height: 24 / 20,
              color: Color(0xff6200EE),
            ),

            headline5: TextStyle(
              fontSize: 24.0,
              fontWeight: FontWeight.w600,
              letterSpacing: 0.15,
            ),

            headline4: TextStyle(
              fontSize: 18.0,
              fontWeight: FontWeight.w600,
              letterSpacing: 0.15,
            ),

            subtitle2: TextStyle(
              fontSize: 17.0,
              fontWeight: FontWeight.w500,
              letterSpacing: 0.25,
              height: 20 / 17,
              color: Colors.black87,
            ),

            bodyText1: TextStyle(
              fontSize: 14.0,
              fontWeight: FontWeight.w400,
              letterSpacing: 0.25,
              height: 20 / 14.0,
            ),
          ),
        ), 
```

**Comment by florianh01** [comment]
As further information: This only happens in light mode and only when I use .copyWith().

**Comment by florianh01** [comment]
Here is the basic flutter app to reproduce this issue:
```

import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: FlexColorScheme.light(
        scheme: FlexScheme.aquaBlue,
        appBarElevation: 4.0,
      ).toTheme.copyWith(
            textTheme: TextTheme(
              headline4: TextStyle(fontSize: 32),
            ),
          ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Text(
              'You have pushed the button this many times:',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ),
    );
  }
}

```

When deleting the copyWith() part, the text turns black again.

**Comment by rydmike** [comment]
I see, if you do `..copyWith()` (note the two dots) instead, it should fix your issue. It did when I tested. 
The `copyWith` will then use the object returned by the `toTheme` and use the `copyWith` on that `ThemeData`. With just one dot we are still operating on default null theme data.

You should do the same on dark mode to ensure you have the right white/black typography for the theme mode.

If for example you had done the ThemeData definitions via final objects and then used copyWith on it, you would not have run into this little Dart gotcha. Quite a common error actually.

Doing it in one go with the .. cascade operator is perfectly fine, and what it exists for.

Text theme definition is btw very involved in the ThemeData object, defining nad building it correctly from scratch is quite tricky, but also doable, this from ThemeData.dart file:

```dart
   assert(colorScheme?.brightness == null || brightness == null || colorScheme!.brightness == brightness);
   final Brightness _brightness = brightness ?? colorScheme?.brightness ?? Brightness.light;
   final bool isDark = _brightness == Brightness.dark;
   : 
   platform ??= defaultTargetPlatform;
    typography ??= Typography.material2014(platform: platform);
    TextTheme defaultTextTheme = isDark ? typography.white : typography.black;
    TextTheme defaultPrimaryTextTheme = primaryIsDark ? typography.white : typography.black;
    TextTheme defaultAccentTextTheme = accentIsDark ? typography.white : typography.black;
    if (fontFamily != null) {
      defaultTextTheme = defaultTextTheme.apply(fontFamily: fontFamily);
      defaultPrimaryTextTheme = defaultPrimaryTextTheme.apply(fontFamily: fontFamily);
      defaultAccentTextTheme = defaultAccentTextTheme.apply(fontFamily: fontFamily);
    }
    textTheme = defaultTextTheme.merge(textTheme);
    primaryTextTheme = defaultPrimaryTextTheme.merge(primaryTextTheme);
    accentTextTheme = defaultAccentTextTheme.merge(accentTextTheme);

```

**Comment by florianh01** [comment]
Thanks for your quick support!

I tried the two dots, but now everything what's inside my copyWith() is ignored. My App uses the default TextTheme now again. But the colors are right again. :)

**Comment by rydmike** [comment]
Hmm... Seems like TextTheme's is tricky, you might indeed have to build a TextTheme from scratch to get it right. Try this: for the light theme:

```dart
      theme: FlexColorScheme.light(
        scheme: FlexScheme.aquaBlue,
        appBarElevation: 4.0,
      ).toTheme.copyWith(
            textTheme: const TextTheme(
              headline6: TextStyle(
                fontSize: 20.0,
                fontWeight: FontWeight.w500,
                letterSpacing: 0.15,
                height: 24 / 20,
              ),
              headline5: TextStyle(
                fontSize: 24.0,
                fontWeight: FontWeight.w500,
                letterSpacing: 0.15,
              ),
              headline4: TextStyle(
                fontSize: 18.0,
                fontWeight: FontWeight.w600,
                letterSpacing: 0.15,
              ),
              subtitle2: TextStyle(
                fontSize: 17.0,
                fontWeight: FontWeight.w500,
                letterSpacing: 0.25,
                height: 20 / 17,
              ),
              bodyText1: TextStyle(
                fontSize: 14.0,
                fontWeight: FontWeight.w400,
                letterSpacing: 0.25,
                height: 20 / 14.0,
              ),
            ).merge(
                Typography.material2018(platform: defaultTargetPlatform).black),
          ),
```

Of curse you have to decide if you want the material2014 or 2014 typography as a base, this gave me this in the demo app I setup:

![image](https://user-images.githubusercontent.com/39990307/129932958-c34fe5a1-1ea4-4a27-91fb-ebd80f815ced.png)


for dark theme you obviously need:

```dart
            ).merge(
                Typography.material2018(platform: defaultTargetPlatform).white),
          ),
```

And of course to get access to `defaultTargetPlatform` you need to import:

`import 'package:flutter/foundation.dart'; `

**Comment by rydmike** [comment]
I should probably expose TextTheme to make it easier to work with custom text themes typography layout, it is a bit nasty, but it is so too with ThemeData too, if you want to do it right, but I could hide that complexity.

**Comment by florianh01** [comment]
> I should probably expose TextTheme to make it easier to work with custom text themes typography layout, it is a bit nasty, but it is so too with ThemeData too, if you want to do it right, but I could hide that complexity.

Just as feedback: I actually like this idea as it becomes more of a replacement for the standard ThemeData.from () widget. But I also think the current solution with merge () is great.

Because my TextThemes didn't work at the beginning, I came up with the idea to use the not recommended way with .toScheme.

Anyways: Thanks for this great support! Theming in Flutter has always been super cumbersome for me, but I'm completely satisfied with the current setup with your package now. Thank you!

**Comment by rydmike** [comment]
Thanks @florianh01 ! 😃  

I had not actually focused so much on making setting up the TextTheme in ThemeData simpler with Flex**Color**Scheme, but this experiment and feedback certainly made me realize it could be useful too.

Mostly I've been happy with just modifying the default font for the base theme, but yes if you want to change the standard text styles it is a bit tricky and a pain. It is also a bit "risky", since many built in Material Widgets depends on the styles, so when you change them in your ThemeData you will also change the text style that the built in Widget use. Which can of course be just the desired effect with a well designed custom TextTheme. 

Sadly there is no good documentation on what Material Widgets depends on what text style, so that you can know what is impacted by your changes. Of course as long as just tweak them slightly form default sizes and latter spacing, you should be fine, with respect to what default Material widgets expect to find and are designed to work with.

There is an article that comes with an Excel file that lists what text styles key widgets use, it is a bit old but still mostly relevant and contains tons of other goodies.

It is still the best article I have seen on Flutter TextTheme's : https://www.didierboelens.com/2020/05/material-textstyle-texttheme/

**Comment by florianh01** [comment]
This Excel is actually pretty cool. Thanks! Thankfully I only made slight changes to my TextStyles.

And you're right, with the growth of Flutter, theming has become more and more opaque and inconsistent. - Unfortunately the Flutter Team is in a dead end if you don't want to introduce breaking changes.
So I'm all the more happy that there are packages like these that address these issues.
