### ISSUE TITLE
textTheme does not inherit colorScheme when used in copyWith 

### ISSUE THREAD

**Issue by Prn-Ice** [rydmike/flex_color_scheme#15]
I created a color scheme but changed the default `textTheme`, now all fonts do not inherit colorscheme.

I changed the `textTheme` by doing this

```dart
FlexColorScheme.light(
      colors: const FlexSchemeData(
        name: 'Theme',
        description: 'Default theme.',
        light: FlexSchemeColor(
          primary: two62626,
          primaryVariant: Colors.black,
          secondary: two4B57A,
          secondaryVariant: zeroE9F64,
          appBarColor: Colors.white,
          error: fF6A6A,
        ),
        dark: FlexSchemeColor(
          primary: Color(0xFF9E7389),
          primaryVariant: Color(0xFF775C69),
          secondary: Color(0xFF738F81),
          secondaryVariant: Color(0xFF5C7267),
        ),
      ).light,
      surface: Colors.white,
      background: Colors.white,
      onPrimary: Colors.white,
      onSecondary: Colors.white,
      onSurface: two62626,
      onBackground: two62626,
      onError: Colors.white,
      scaffoldBackground: f7F8FA,

      /// Visual density
      visualDensity: FlexColorScheme.comfortablePlatformDensity,

      /// Fonts
      fontFamily: R.fontFamily.avenir_next,
    ).toTheme.copyWith(
          textTheme: _textTheme,
        );

```

**Comment by Prn-Ice** [comment]
Thanks a lot, looking forward to the next release. I am trying out your fix now, thanks for the awesome package.

**Comment by Prn-Ice** [comment]
What worked for me was
```dart
_flexLightColorScheme.toTheme.copyWith(textTheme: ... ).merge(_flexLightColorScheme.toTheme.textTheme),

```

**Comment by rydmike** [comment]
Yes that will work too, you can certainly merge the full `textTheme` that way as well.

On my todo list for next version is to expose a `textTheme` property that does behind the scenes, and it also becomes a bit more effective then since the extra `copyWith` and `toTheme` are not needed then.

Glad you figured it out, but yeah this should not be this tricky, it need its own property to simplify it. 

Thanks for the feedback and for pointing out doing this is a bit of challenge, as shown above you were not the first one to think so. This is btw just as tricky in Flutter if you have an existing `ThemeData` object and you want to create a new one with adjusted `TextTheme`. Does not mean we cannot make it easier. 

Closing this issue as solved and I have the improvement on my todo list as well 😃
