### ISSUE TITLE
^4.0.0 is not exists

### ISSUE THREAD

**Issue by theowenyoung** [rydmike/flex_color_scheme#18]
Hi, the readme is updated to `^4.0.0`, but the pub repository does not.

When will it be published?

Thanks!

**Comment by rydmike** [comment]
Hi @theowenyoung,

Thanks for your early interest in v4. Correct observation, it is not released yet. It is WIP (Work in Progress state).

Here is a list of what is coming:
https://github.com/rydmike/flex_color_scheme/blob/master/CHANGELOG.md

Only me working on this project, so I've been a bit lazy and working against master (won't do that again since this has become fairly popular project and it may confuse people). this was also originally only going to be some small updates, but it kind of expanded to a major new version and has taken much more time than I planned.

I'm still working on fine tuning some details and finalizing the new and updated examples.
Example 5 is the one I have been sharing showing on Twitter. I still need to add local persistence to it. It has all the hooks for it prepared.

As before all examples/tutorial, will also be available as live web demos.

The documentation will get a complete revision as well, before stable 4.0.0 release on pub.dev.

I plan to release some dev versions, that may still not have final v4 API, before I release the final v4.0.0. release. I don't think there will be any major changes anymore to API. Maybe only some fine tuning to their behavior and maybe add a few more sub-themes. So once I release the dev version it should be safe to use already then. However, dev release will firs be with no to limited docs, other than the updated examples that are a guide in themselves, plenty of guiding comments in them.

The readme doc will continue to improve and develop, until it is ready, at which point I will release also the stable 4.0.0.

All API docs have been written during development, so they are ready now as well.

First dev release of 4.0.0 is maybe a few days away. Fell free to play with version on master on GitHub if you are really curios 😃 


BR
Mike

**Comment by rydmike** [comment]
Version 4 has been released. Closing this issue! 😃
