### ISSUE TITLE
No android navigation bar in themes playground simulator when running in web platform

### ISSUE THREAD

**Issue by venkata-reddy-dev** [rydmike/flex_color_scheme#188]
### Issue: 

There is no representation of android system navigation bar in simulator of themes playground. and as a developer i know technically we can't achieve this in simulator in simpler way. the ideal way is run themes playground in android device to see the preview of changes. 

### Solution / Suggestion:
 Just add some helpful message in section of **android system navigation bar**. so that it helps themes playground users.

<img width="1429" alt="Screenshot 2023-09-08 at 7 38 24 PM" src="https://github.com/rydmike/flex_color_scheme/assets/32235964/5323129a-9a7a-4d2f-973c-256bf36358ab">

**Comment by rydmike** [comment]
Hi @RR-Reddy,

Thanks for the suggestion. The **Theme simulator** is just wrapping a few simple demo "app" widgets in a "device_frame" view provided by package https://pub.dev/packages/device_frame. So yes it is not in anyway or form representative of a real device or even when using a device emulator or simulator.


It is only intended to give a rough idea of the look and feel of an app using the active theme on a selected approximation of a device, of each included demo app.

Sure a brief explanation of this might be a helpful addition to the Theme simulation info expand part. I'll add a mentioned of this in the next update.

![Screenshot 2023-09-14 at 15 45 59](https://github.com/rydmike/flex_color_scheme/assets/39990307/c2b725d8-b82f-4d65-a310-c34eced06364)

Technically I could add a mock navigation bar on the bottom of all the devices, but that might be equally confusing as it would not really do anything. 😄

**Comment by rydmike** [comment]
Thank you for your patience waiting for version 8.0.0.

**FlexColorScheme** package dev release 8.0.0-dev.1 has been published. This is a BIG update with breaking changes and many new features. It has its own dev pre-release of the [**Themes Playground**](https://rydmike.com/flexcolorscheme/themesplayground-dev) as well, feel free to take a peak. No new API changes are planned for the stable 8.0.0 release from this dev.1 release.

We would appreciate any feedback about found issues from early adopters. 

* [Doc site has some pre-info](https://docs.flexcolorscheme.com/)
* [Dev release of PKG here](https://pub.dev/packages/flex_color_scheme/versions/8.0.0-dev.1)
* [The PKG changelog has the most detailed info](https://pub.dev/packages/flex_color_scheme/versions/8.0.0-dev.1/changelog)

This issue is solved in the new release, but I will not close this issue until the stable version of 8.0.0 has been released. 

**FOR INFO** there will be no new features or changes in it compared to this one. Only any issues found from the QA assurance will be addressed. The stable release will also include many doc updates, but docs site will continue to be edited and revised AFTER the 8.0.0 stable release.

![Screenshot 2024-10-14 at 2 49 24](https://github.com/user-attachments/assets/012d3a0f-291e-4297-a378-4bab80ee7a55)
