### ISSUE TITLE
Better organization of enabled and disabled chips and rename elevated chips.

### ISSUE THREAD

**Issue by TahaTesser** [rydmike/flex_color_scheme#191]
The current organisation puts all chips into a single section which makes it challenging to distinguish enabled and disabled chips especially when applying custom colors.

              
![Screenshot 2023-09-28 at 16 18 38](https://github.com/rydmike/flex_color_scheme/assets/48603081/0fa0e789-5001-4519-a401-7385431d0a49)

### Suggestion

Separate chips like this
![Screenshot 2023-09-28 at 16 24 08](https://github.com/rydmike/flex_color_scheme/assets/48603081/d56e7790-c891-4e1c-9de9-f3b09174e961)

**Comment by rydmike** [comment]
Have a bunch of theming features to test and add to **Chips** as well, so this will be a trivial and logical cleanup of Playground UI when working on those features.

The current design is legacy from when a lot widgets shared the same panel and we wanted to fit them in a compact responsive view using a simple `Wrap` for all of the different `Chip` variants. Current design allows for this layout much better and changing to it is indeed a good suggestion.

**Comment by rydmike** [comment]
Since it is a very responsive layout, this is the best I can do with Wraps. It will still have a 3 col layout mode in some layout sizes, which is not ideal, but just use a bigger screen and you never see that 😃 

With Grid and LayoutBuilder I could do better layout that avoids 3 columns, but I don't think it so necessary for this presentation

https://github.com/rydmike/flex_color_scheme/assets/39990307/10d00531-9430-4c1e-aea0-7a88df717840

---

Q: @TahaTesser what do you mean with rename elevated chips? I'm using the names the Widgets have in Flutter at te moment.

---

Observation:

I don't think it is still possible to create themes where each chip type `Action`, `Filter`, `Choice` and `Input` all use from each other different foreground, background colors and disabled color styles, for disabled foreground and background. But I have not checked with all the latest improvements on master channel yet, but last time I looked it was not possible. 😃

**Comment by TahaTesser** [comment]
> Q: @TahaTesser what do you mean with rename elevated chips? I'm using the names the Widgets have in Flutter at te moment.

I was thinking if it could  be better to have names like `FilterChip` and `Elevated FilterChip' to see which ones are elevated. 
As the chips blend when you modify elevation, can't disguise which is elevated variant.

**Comment by rydmike** [comment]
Thank you for your patience waiting for version 8.0.0.

**FlexColorScheme** package dev release 8.0.0-dev.1 has been published. This is a BIG update with breaking changes and many new features. It has its own dev pre-release of the [**Themes Playground**](https://rydmike.com/flexcolorscheme/themesplayground-dev) as well, feel free to take a peak. No new API changes are planned for the stable 8.0.0 release from this dev.1 release.

We would appreciate any feedback about found issues from early adopters. 

* [Doc site has some pre-info](https://docs.flexcolorscheme.com/)
* [Dev release of PKG here](https://pub.dev/packages/flex_color_scheme/versions/8.0.0-dev.1)
* [The PKG changelog has the most detailed info](https://pub.dev/packages/flex_color_scheme/versions/8.0.0-dev.1/changelog)

This issue is solved in the new release, but I will not close this issue until the stable version of 8.0.0 has been released. 

**FOR INFO** there will be no new features or changes in it compared to this one. Only any issues found from the QA assurance will be addressed. The stable release will also include many doc updates, but docs site will continue to be edited and revised AFTER the 8.0.0 stable release.
