### ISSUE TITLE
The example should be updated when PersistentBottomSheetController's type param has been removed

### ISSUE THREAD

**Issue by huynguyennovem** [rydmike/flex_color_scheme#222]
Hello Mike,
I just pulled your example and found there is an issue on and afterward: https://github.com/rydmike/flex_color_scheme/blob/be91c990c9b99afadd56a65b00b02412a00fe13a/example/lib/example5_themes_playground/widgets/panels/theme_simulator/app_example_material3/component_screen.dart#L1656

```console
The type 'PersistentBottomSheetController' is declared with 0 type parameters, but 1 type arguments were given.
```

I'm on the latest stable channel 3.19.3. I see this error is caused by the change at https://github.com/flutter/flutter/pull/137791. The fix is simple, just remove `<void>` in some error places there.

**Comment by rydmike** [comment]
Thanks @huynguyennovem a good and known find,

I am aware of this change in the framework, and this change in the SDK has been addressed in the yet unreleased branch [7-4-0](https://github.com/rydmike/flex_color_scheme/tree/version-7-4-0), some time ago.

I now added a link to this report in the chnangelog, in the 7-4-0 branch that also already fixes this issue in example 5. I did not merge the otherwise correct fix PR you submitted (thank you for the submission), since the issue has already been fixed in this branch prior to the submission of the fix.

Next I need to find the time to get all the other things done that I have planned for version 7.4.0. Been very busy with my day job project. 

I had planned to postpone making a new release of FlexColorScheme until version 8.0.0, and also include some breaking changes in it. But I think I will instead go back to making all the planned 7.4.0 features and postpone the breaking changes. 

With next Flutter stable release, after 3.19.x, there will again very likely be many breaking changes in theming due to new `ColorScheme` colors. So at that point I need to release a breaking version of FlexColorScheme as well.

I now need to get version 7.4.0 out maybe next week, and then start a new 8.0.0 branch and work against Flutter master channel with it, to prepare for coming next Flutter release.

I will keep this issue report open until version 7.4.0 has been released.

**Comment by huynguyennovem** [comment]
As usual, your feedback and issue description (on Flutter repo) are always informative. Thank you for sharing. I'm using `flex_color_scheme` for my new app, this is a great package for theming Flutter apps. Since you have fixed this issue for the upcoming release, I will close the PR :)

**Comment by rydmike** [comment]
Thank you for your patience waiting for version 8.0.0.

**FlexColorScheme** package dev release 8.0.0-dev.1 has been published. This is a BIG update with breaking changes and many new features. It has its own dev pre-release of the [**Themes Playground**](https://rydmike.com/flexcolorscheme/themesplayground-dev) as well, feel free to take a peak. No new API changes are planned for the stable 8.0.0 release from this dev.1 release.

We would appreciate any feedback about found issues from early adopters. 

* [Doc site has some pre-info](https://docs.flexcolorscheme.com/)
* [Dev release of PKG here](https://pub.dev/packages/flex_color_scheme/versions/8.0.0-dev.1)
* [The PKG changelog has the most detailed info](https://pub.dev/packages/flex_color_scheme/versions/8.0.0-dev.1/changelog)

This issue is solved in the new release, but I will not close this issue until the stable version of 8.0.0 has been released. 

**FOR INFO** there will be no new features or changes in it compared to this one. Only any issues found from the QA assurance will be addressed. The stable release will also include many doc updates, but docs site will continue to be edited and revised AFTER the 8.0.0 stable release.

**Comment by rydmike** [comment]
Closing this issue, as it is fixed in the latest release: https://pub.dev/packages/flex_color_scheme
