### ISSUE TITLE
Support tone-based surface and surface container ColorScheme roles

### ISSUE THREAD

**Issue by wildsylvan** [rydmike/flex_color_scheme#228]
material 3 got some updates regarding the color roles

see here: https://github.com/flutter/flutter/issues/115912

**Comment by rydmike** [comment]
Thank you, yes I am aware. This will be added after the feature lands in the Flutter stable channel. It will be a breaking change since the entire ColorScheme needs new colors and it also deprecates some old colors. It will be available in FlexColorScheme v8.0.0.

**Comment by rydmike** [comment]
Thank you for your patience waiting for version 8.0.0.

**FlexColorScheme** package dev release 8.0.0-dev.1 has been published. This is a BIG update with breaking changes and many new features. It has its own dev pre-release of the [**Themes Playground**](https://rydmike.com/flexcolorscheme/themesplayground-dev) as well, feel free to take a peak. No new API changes are planned for the stable 8.0.0 release from this dev.1 release.

We would appreciate any feedback about found issues from early adopters. 

* [Doc site has some pre-info](https://docs.flexcolorscheme.com/)
* [Dev release of PKG here](https://pub.dev/packages/flex_color_scheme/versions/8.0.0-dev.1)
* [The PKG changelog has the most detailed info](https://pub.dev/packages/flex_color_scheme/versions/8.0.0-dev.1/changelog)

This issue is solved in the new release, but I will not close this issue until the stable version of 8.0.0 has been released. 

**FOR INFO** there will be no new features or changes in it compared to this one. Only any issues found from the QA assurance will be addressed. The stable release will also include many doc updates, but docs site will continue to be edited and revised AFTER the 8.0.0 stable release.

**Comment by rydmike** [comment]
Closing this issue, as it is supported in the latest release: https://pub.dev/packages/flex_color_scheme
