### ISSUE TITLE
Lack of inputDecoratorSuffixIconSchemeColor properties

### ISSUE THREAD

**Issue by laterdayi** [rydmike/flex_color_scheme#231]
Lack of inputDecoratorSuffixIconSchemeColor properties

```
inputDecoratorIsFilled: false,
inputDecoratorPrefixIconSchemeColor: SchemeColor.primary,
```

I can set the inputDecoratorPrefixIconSchemeColor, but there was no inputDecoratorSuffixIconSchemeColor configuration items

**Comment by rydmike** [comment]
Thanks @laterdayi, yes I'm aware this one is not included. **FlexColorScheme** does not contain APIs for everything you can do with `ThemeData`, nor does it strive to provide a complete replacement API for it, more like making tedious parts more convenient. 

You can always add missing theming with `.copyWith` on the `ThemeData` and component theme data it produces.

However, this one would be quite handy to have in FlexColorScheme, so I will try to add to the next version.

**Comment by rydmike** [comment]
Thank you for your patience waiting for version 8.0.0.

**FlexColorScheme** package dev release 8.0.0-dev.1 has been published. This is a BIG update with breaking changes and many new features. It has its own dev pre-release of the [**Themes Playground**](https://rydmike.com/flexcolorscheme/themesplayground-dev) as well, feel free to take a peak. No new API changes are planned for the stable 8.0.0 release from this dev.1 release.

We would appreciate any feedback about found issues from early adopters. 

* [Doc site has some pre-info](https://docs.flexcolorscheme.com/)
* [Dev release of PKG here](https://pub.dev/packages/flex_color_scheme/versions/8.0.0-dev.1)
* [The PKG changelog has the most detailed info](https://pub.dev/packages/flex_color_scheme/versions/8.0.0-dev.1/changelog)

This issue is solved in the new release, but I will not close this issue until the stable version of 8.0.0 has been released. 

**FOR INFO** there will be no new features or changes in it compared to this one. Only any issues found from the QA assurance will be addressed. The stable release will also include many doc updates, but docs site will continue to be edited and revised AFTER the 8.0.0 stable release.
