### ISSUE TITLE
flex_color_scheme >=7.2.0 depends on flex_seed_scheme ^1.4.0

### ISSUE THREAD

**Issue by sgehrman** [rydmike/flex_color_scheme#233]
Because flex_color_scheme >=7.2.0 depends on flex_seed_scheme ^1.4.0 and flex_color_picker >=3.5.0 depends on flex_seed_scheme ^2.0.0, flex_color_scheme >=7.2.0 is incompatible with flex_color_picker >=3.5.0.

**Comment by rydmike** [comment]
Hi @sgehrman,

The dependency warning is correct and expected.

I'm guessing you are using `flex_color_picker 3.5.0` as a direct dependency to get this error?Which also means you are already using Flutter 3.22, as the picker 3.5.0 requires min Flutter 3.22.0. 

For now, pin an older version of the flex_color_picker that does not have this conflict, step down in version until you get one without conflict. First try `flex_color_picker 3.5.0`, then `flex_color_picker 3.4.1` and so on. Pinned means no ^ or >=. You should as you step down find the highest one that works with your combination of flex color picker and flex color scheme.

Since (if) you are using Flutter 3.22, please be aware that flex_color_scheme 7.3.1 and earlier versions are not fully compatible with **Flutter 3.22**.

https://docs.flexcolorscheme.com/
 
![Screenshot 2024-05-19 at 02 44 26](https://github.com/rydmike/flex_color_scheme/assets/39990307/d513a11b-774a-4d57-8902-3f1810272110)


Pending `flex_color_scheme 8.0.0`, will fix the dependency conflict and also provide full Flutter 3.22 compatibility.

**Comment by rydmike** [comment]
Thank you for your patience waiting for version 8.0.0.

**FlexColorScheme** package dev release 8.0.0-dev.1 has been published. This is a BIG update with breaking changes and many new features. It has its own dev pre-release of the [**Themes Playground**](https://rydmike.com/flexcolorscheme/themesplayground-dev) as well, feel free to take a peak. No new API changes are planned for the stable 8.0.0 release from this dev.1 release.

We would appreciate any feedback about found issues from early adopters. 

* [Doc site has some pre-info](https://docs.flexcolorscheme.com/)
* [Dev release of PKG here](https://pub.dev/packages/flex_color_scheme/versions/8.0.0-dev.1)
* [The PKG changelog has the most detailed info](https://pub.dev/packages/flex_color_scheme/versions/8.0.0-dev.1/changelog)

This issue is solved in the new release, but I will not close this issue until the stable version of 8.0.0 has been released. 

**FOR INFO** there will be no new features or changes in it compared to this one. Only any issues found from the QA assurance will be addressed. The stable release will also include many doc updates, but docs site will continue to be edited and revised AFTER the 8.0.0 stable release.

**Comment by rydmike** [comment]
Closing this issue, as it is fixed in the latest release: https://pub.dev/packages/flex_color_scheme
