### ISSUE TITLE
default light mode on Tabs is white text on white background

### ISSUE THREAD

**Issue by sgehrman** [rydmike/flex_color_scheme#234]
I had to add
      tabBarStyle: FlexTabBarStyle.forBackground,

Why is a default broken?

**Comment by rydmike** [comment]
If you are using **FlexColorScheme 7.3.1** or earlier with **Flutter 3.22**, this might happen.

FlexColorScheme 7.3.1 and earlier are not fully compatible with Flutter 3.22 that contains many substantial breaking changes in how it handles surface colors.

https://docs.flexcolorscheme.com/
![Screenshot 2024-05-19 at 02 44 26](https://github.com/rydmike/flex_color_scheme/assets/39990307/05355c8a-d829-4466-9420-8a8291410bf4)

---

If you are using Flutter 3.19 or earlier, please provide a code sample to reproduce your issue, and we will look into it.

**Comment by sgehrman** [comment]
That's disappointing as I spent the morning converting my app.  Do you think it will be out in a week or so, or longer?

**Comment by rydmike** [comment]
Hi @sgehrman,

About this issue that you reported. I have been unable to reproduce it, even when using FCS 7.3.1 with Flutter 3.22.x or 3.24.x.

The themed `TabBar` color by default follows Flutter SDK defaults for M3 and M2 mode respectively. 

In M3 mode the default `AppBar` is surface colored, so the default `TabBar` works by default also on normal surface (background) colors. 

**M3 mode defaults**
![Screenshot 2024-08-17 at 3 53 31](https://github.com/user-attachments/assets/1b621697-165b-437b-9cb8-31ac7fa5cd51)

In M2 mode the `AppBar` is primary colored by default, this color typically requires light contrast (white, or similar). So FCS and Flutter uses that by default in legacy M2 mode. In Flutter and thus also in FCS there is no way to theme a `TabBar` so it fits both on a place requiring light and dark contrast colors at the same time. You have to choose one. In M2 the default `AppBar` style creates this situation, but in M3 the AppBar is surface colored by default and `TabBar` can thus fit both in `AppBar` and on other surfaces by default

**M2 mode defaults**
![Screenshot 2024-08-17 at 4 01 27](https://github.com/user-attachments/assets/32793558-a6ae-4800-b814-a7618c615309)


You can however also make `TabBar` automatically follow the selected `AppBarStyle` or Scheme color it is set to use, by using `FlexTabBarStyle.forAppBar` so it follows the `AppBar`:s style automatically using correct contrast for it regardless of what color it uses:

https://github.com/user-attachments/assets/f0ffaf9a-d5f1-4d33-83c4-326ea974c71a

In **FlexColorScheme** in M2 the `FlexTabBarStyle.forAppBar` is default behavior. However, in M3 mode, the default behavior is the `FlexTabBarStyle.flutterDefault` following the SDK defaults, but you can change it to  `FlexTabBarStyle.forAppBar` or `FlexTabBarStyle.forBackground` as needed.

If you use e.g `primary` color on your `AppBar`, then this requires white (light) contrast when the `TabBar` is used in an `AppBar`, which is its primary usage location in Material design, and hence the default.

Thus when you have an `AppBar` that requires reverse color to what is needed on surface colors, and do not intend to use the `TabBar` in the `AppBar`, but on surface (background) colors, then you **do indeed need to set `FlexTabBarStyle.forBackground`** to tune it to colors that fit on surface (background) colors instead. It cannot fit both requirements at once, it has only one themed style. The same situation occurs even if you use vanilla `ThemeData` without FlexColorScheme. It is expected behavior. 

https://github.com/user-attachments/assets/39b7c24a-9bd6-4662-a918-bf3daa4d81b5

Hope this answers the question.

If you have an issue where it does not work as described and above, please post a sample and we can reopen revisit the issue.

---

BTW: FlexColorScheme 8.0.0 is finally progressing steadily now that I am finally able to work on it.

Some more info about it and link to the 8.0.0-dev change log with some progress status: https://github.com/rydmike/flex_color_scheme/issues/247#issuecomment-2293958358
