### ISSUE TITLE
[bug] Instant Splash not triggered on short taps

### ISSUE THREAD

**Issue by dickermoshe** [rydmike/flex_color_scheme#239]
Title says it all

https://github.com/rydmike/flex_color_scheme/assets/75931499/66a1ec93-ae37-44d3-89a8-2bec8da0c990

**Comment by rydmike** [comment]
Thanks, yes I agree it does not work well on very quick taps.

I added the same fix that I did for the [adaptive_theme_demo](https://github.com/rydmike/adaptive_theme_demo) repo, seemed to work well in it, so it should probably do so here too.

I won't land this fix until version 8.0.0 though, so keeping it open until then.

**Comment by rydmike** [comment]
Thank you for your patience waiting for version 8.0.0.

**FlexColorScheme** package dev release 8.0.0-dev.1 has been published. This is a BIG update with breaking changes and many new features. It has its own dev pre-release of the [**Themes Playground**](https://rydmike.com/flexcolorscheme/themesplayground-dev) as well, feel free to take a peak. No new API changes are planned for the stable 8.0.0 release from this dev.1 release.

We would appreciate any feedback about found issues from early adopters. 

* [Doc site has some pre-info](https://docs.flexcolorscheme.com/)
* [Dev release of PKG here](https://pub.dev/packages/flex_color_scheme/versions/8.0.0-dev.1)
* [The PKG changelog has the most detailed info](https://pub.dev/packages/flex_color_scheme/versions/8.0.0-dev.1/changelog)

This issue is solved in the new release, but I will not close this issue until the stable version of 8.0.0 has been released. 

**FOR INFO** there will be no new features or changes in it compared to this one. Only any issues found from the QA assurance will be addressed. The stable release will also include many doc updates, but docs site will continue to be edited and revised AFTER the 8.0.0 stable release.

**Comment by dickermoshe** [comment]
Super exciting!!!!

@rydmike There is a delay whenever values are changed on the new site.
Seems like some smoothing going on. (easy in)


https://github.com/user-attachments/assets/06e3c425-9ac2-4a1e-99d4-aa240a9b4654

**Comment by rydmike** [comment]
Yes this is expected.

When you change any Slider value, even just one step, or many, the theme animates from pervious value(s) to new value(s) for every value you slide via, what you are seeing is one or multiple theme transitions. This causes a delay in the result for the `Duration` of Flutter's built in Theme transition animation.

All component style updates in the Playground itself also use the theme you modify. If I would update the demo components directly to set new value, they would change instantly, but the purpose of Playground is to only do any change to any component shown and used in the app itself also and ONLY via the theme you change and make in the app. Every little change has theme transition animation from previous value to the new value. When operating and border radius with Slider, this looks like a delay, and it is since the theme is animating to each new new value you set/drag the Slider to.
