### ISSUE TITLE
IconButton extensions not working with FlexThemeData

### ISSUE THREAD

**Issue by brunodmn** [rydmike/flex_color_scheme#247]
Variations of `IconButton` won't work. ` IconButton.filled`, `IconButton.filledTonal`,`IconButton.outlined` all look the same.

When NOT using FlexThemeData, works as expected.

Using sdk: ">=3.4.3 <4.0.0" and flex_color_scheme: ^7.3.1

**Comment by brunodmn** [comment]
Sorry for that, I just realized it works as expected if I set `useMaterial3: true` on FlexThemeData. 
I thought it was deprecated, as it is in stable Flutter SDK.
Suggestion would be to `useMaterial3: true` as default on FlexThemeData or deprecate it as it is on Flutter.

**Comment by rydmike** [comment]
Yes FlexColorScheme 7.3.1 and earlier versions still default the flag `useMaterial3` to false. 

Changing its default value to `true` would be a breaking change to 7.x.x releases, so version 7 will keep the default false.

However, the version 8.0.0 that is currently WIP phase, **has changed the default for `useMaterial3` to `true`**. Version 8.0.0 anyway has to deal with 100:s of breaking changes that Flutter 3.22 introduced anyway and needs to break a lot of past features, so we are using the opportunity to also break this flag default and a number f other older legacy defaults.

The reason why Version 8.0.0 is taking so long is because all the changes introduced in Flutter 3.22 to Material theming were really massive and they broke a lot of subtle features in FCS.

Please do note that FlexColorScheme 7.3.1 is not fully compatible with Flutter 3.22 and later, but Version 8.0.0 will be and it will also introduce many new features. It will however also introduce a large number of breaking changes since Flutter 3.22 broke hundreds of tests in FCS and also features that can no longer be recreated the same wa,y due to deprecation of important color FCS depended on for many of its features. Equivalent features will be available in 8.0.0, but some past ones cannot be made the same way.

https://docs.flexcolorscheme.com/
![Screenshot 2024-08-16 at 21 16 15](https://github.com/user-attachments/assets/5b3360d4-a0cd-4016-ba89-8bb57de8e8d3)

Version 8.0.0 it coming along nicely now and you cxan check daily progress in the changelog here: https://github.com/rydmike/flex_color_scheme/blob/version-8-0-0/CHANGELOG.md

---

Please also note that the flag `useMaterial3` is **NOT** yet deprecated in Flutter, not even in latest master. Setting it to false and using Material2 is still possible without any deprecation warning and perfectly valid still. It is however mentioned in the doc comments that it will be deprecated as follows:

> In the long run this flag will be deprecated and eventually only Material 3 will be supported. We recommend that applications migrate to Material 3 as soon as that's practical. Until that migration is complete, this flag can be set to false.

**Comment by brunodmn** [comment]
Hello @rydmike,

 Thank you for your quick reply and information. 

 You really did a great job on this package, makes life a lot easier on theming, I am sure all community really appreciate it.

 Thanks a lot.
