### ISSUE TITLE
iOS build failing with Error: No named parameter with the name 'locale'.

### ISSUE THREAD

**Issue by vipseixas** [rydmike/flex_color_scheme#260]
I was using version 8.0.0 and everything works as expected at development, but when I tried to generate an iOS release (using codemagic), I got this error:

> Failed to build iOS app
> Error (Xcode): ../../../.pub-cache/hosted/pub.dev/flex_color_scheme-8.0.0/lib/src/flex_sub_themes.dart:2559:7: Error: No named parameter with the name 'locale'.
> 
> Encountered error while archiving for device.

The command line used was:

`flutter build ipa --release --flavor ${FLAVOR} -t lib/main/main_${FLAVOR}.dart --build-number=$PROJECT_BUILD_NUMBER --export-options-plist=/Users/builder/export_options.plist
`

Flutter version is 3.22.2 and Xcode version is 15.4.

Downgrading to 7.3.1 resolves the problem and APK builds work with both versions.

**Comment by rydmike** [comment]
Thanks for the report @vipseixas, looks like my assumption that there were no theming related changes going from Flutter 3.22 to Flutter 3.24 were incorrect. 

When working on the hundreds of changes caused and needed due to Flutter 3.19, I first did so on Flutter 3.22, but later switched to 3.24 when it arrived. I should of course have gone back and checked on Flutter 3.22 before releasing the package with min version constraint Flutter 3.22.0. I just tried too with 3.22, ouch.

The locale API used in the component theme in question is not available before Flutter 3.24.0, so the minimum version constraint for FlexColorScheme V8 should thus be 3.24.0 and not 3.22.0.

I should release a fix with the constraint bumped, but it won't help since it is already out with an incorrect one.

Are you able to update your Flutter project to latest 3.24.4? 

(Flutter 3.27.0 is about to land any day now BTW.)

---

If not, I could release a version called 8.0.0-flut.3.22 (or something like it) without the offending locale API that does not exist in Flutter 3.22. It could be used by those that need a V8 that builds on Flutter 3.22.x. Although I suspect most users have moved on to Flutter 3.24.

**Comment by vipseixas** [comment]
> Are you able to update your Flutter project to latest 3.24.4?

Actually I had to downgrade from this version because of another build problem (something related to non-modular headers used by Firebase libs). I was not using FCS at the time and I just added it to the app a few days ago and ran into this problem. 

> Although I suspect most users have moved on to Flutter 3.24.

I agree and I'm planning on upgrading these Firebase libs and it's likely that I'll be able to go back to 3.24, but for now I can get by with FCS 7.3.1. Maybe just a warning in the docs would suffice. Thanks!

**Comment by rydmike** [comment]
Thanks, and thanks for this find, much appreciated. I should have downgraded and tested on Flutter 3.22.0 myself before releasing it with the 3.22.0 constraint.

Updated the docs site by adding a warning call-out:

![Screenshot 2024-11-13 at 16 07 12](https://github.com/user-attachments/assets/6a933f71-a2de-426d-95e6-3aa9d3c103b4)


It is also on the Migration guide page.

But I will also need to release 8.0.1 as FIX that removes the faulty Flutter 3.22.0 constraint and bumps it to 3.24.0, and update the readme with this info too. 

When I do that, I might as well first upload a version that offers 3.22.0 support for anybody that is stuck there, most will probably move to newer Flutter versions very soon anyway, but version 8 was actually supposed to support Flutter 3.22 as well. Just missed that one Flutter 3.24.0 only API that snuck in there, sigh. There is so much changes and new features in Flutter theming all the time.

**Comment by rydmike** [comment]
@vipseixas For info there is now [8.0.1](https://pub.dev/packages/flex_color_scheme/versions/8.0.1), that fixes the faulty version constraint. There is also info about this issue in its changelog, and info about a version that can be used Flutter 3.22, should anybody need it.

> FlexColorScheme version 8.0.0 requires at least Flutter 3.24.0. The package version constraint claims it should work with 3.22.0 as well, but it uses a single component theming property not available until Flutter 3.24.0. If you need a release of version 8 that is also compatible with Flutter 3.22, you can use [version 8.0.1-dev.3.22](https://pub.dev/packages/flex_color_scheme/versions/8.0.1-dev.3.22) of the package. This release is identical to the **8.0.1** release, but excludes the API not available in Flutter 3.22. Generally, prefer upgrading to Flutter 3.24 or later when using FlexColorScheme version 8.
