### ISSUE TITLE
primaryVariant and secondaryVariant deprecated

### ISSUE THREAD

**Issue by Prn-Ice** [rydmike/flex_color_scheme#32]
With the latest flutter update `Theme.colorScheme.primaryVariant` and `Theme.colorScheme.secondaryVariant` have been deprecated, how do we access `primaryVariant` and `secondaryVariant` declared in `FlexSchemeColor.from()`.

**Comment by rydmike** [comment]
Hi @Prn-Ice thank you for opening the issue and your question.

Yes I know and even knew it was coming. 

You can still use them as before, they do still work, everything is still unbroken and works as before. The deprecation is a pre-warning that the property will go away, usually after about 1 year after deprecation.

You can read about the Flutter policy for deprecated APIs here: https://docs.flutter.dev/resources/compatibility

I am already working on an update that will also deprecate the same properties in FlexColorScheme and introduce the new ones. Plus add support for all the new colors on M3 based ColorScheme.

There are quite a lot of changes due to the new M3 ColorScheme. Introducing them all will take "a few" evenings of coding. The new color properties in M3 based ColorScheme are not yet supported by FlexColorScheme or its built in themes. I also want to try a few different options and try to if possible introduce the new features without any breaking changes in FlexColorScheme too, there will be deprecations in it too of course, but old things should still work too, that is my first target anyway.

I'm trying to see if I can get away with a 4.3.0 new features only release, all old stuff still work. Or if I will need to make a breaking release 5.0.0 to support all the new things. There are some things I would like to improve and old things I would like to clean up too, those would then need a breaking release, if I decide to do them now too, but I will see soon.

I might do a dev pre-release of the package before next stable release, to collect some feedback on the new features too.

**Comment by rydmike** [comment]
Hi @Prn-Ice,

In case you have not noticed it, version 5 of FlexColorScheme is available as dev.2 release here:
https://pub.dev/packages/flex_color_scheme/versions/5.0.0-dev.2

It addresses the issue you mentioned and has many new features. While this is still only a "dev" release and not the final 5.0.0
stable release, there are no planned changes for the final release. It is only in a dev release stage all the doucmentation has been updated to suffcient level too. 
All API docs are already up to date, but the readme is being converted to dedicated documentation site, with a lot more information than it had before.

The **Themes Playground** companion web app for FlexColorScheme has stepped up the game too, with a lot of new features. You can find it here: https://rydmike.com/flexcolorscheme/themesplayground-v5

If you take a look a this Tweet thread you can see Dash telling what you can do with the new version 5 features too.
https://twitter.com/RydMike/status/1511166732496429058?s=20&t=B_wq2Og_tR2EGEV1Mko28Q

I'm closing this issue as done now, enjoy the new version. 💙
