### ISSUE TITLE
feat: add loading screen to web version

### ISSUE THREAD

**Issue by yeikel16** [rydmike/flex_color_scheme#33]
It would be very convenient to add a loading screen to the web version, to show the user that it is taking a while to load the page, since it takes a few seconds to download the `canvaskit` cache

**Comment by rydmike** [comment]
Totally agree. 

I wonder if the latest versions of the Flutter Web embedder adds one automatically? It definitely should imo. I saw some discussions about it earlier, not sure if it ever landed. For the next release, v5 that I'm working on, I update the embedder, see if it is included automatically now, and if not I'll add one myself.

Some really cool new features coming in v5 btw. I'm going to release a dev preview of if before stable release. It contains so many changes that I think it needs some peer review and in the wild testing first. Plus updating all the docs will take time and I'm not going to release stable version before docs are updated as well, and some devs may want to get in on all the new cool CM2 ColorScheme features I'm using in it too, with a bunch of custom helpers and customization to seeded ColorSchemes that the Flutter SDK is lacking at the moment at least.

The Themes Playground app kind of grew out of hand, it was just a small last step in the tutorial as example 5. But it exploded into something of its own. New version for v5 has even more config features. I've also gotten suggestion on making a more step driven / guided UI for it, might do that some day too. I would keep current UI as expert mode though, as it allows at least me to see almost all settings at one glance on a 32" 4k screen 😅

**Comment by yeikel16** [comment]
I was also researching about the loading screen issue and it's still not available in the latest version, the Flutter team is working on something to have a little more control, this is the [issue](https://github.com/flutter/flutter/issues/48468#issuecomment-1013475205).
I was playing with an example to test the WEB version and in the end I ended up implementing one by myself, you can see the web [game-of-life](https://game-of-life-blue-six.vercel.app/), this is the repo of the [example](https://github.com/yeikel16/game_of_life).
It sounds great what this new v5 brings, if you need any kind of help, I would like to contribute. I started to contribute in the open source world and the truth is that it feels very good, and now I can't stop, it feels very good !!

**Comment by rydmike** [comment]
@yeikel16 wanted to say thanks and that I used your loading screen solution. Probably not what Flutter will deliver one day, but until something is supported by the built in web runner directly, I think the solution you had works very well 💙 

It seems to move a bit before the app actually starts, not sure why, but for this purposes it is excellent.

For info, I'm using it in version 5-dev.2 release, link below.

---

## Off topic

The **Themes Playground** companion web app for FlexColorScheme version 5 (package still at v5.0.0-dev.2 release https://pub.dev/packages/flex_color_scheme/versions/5.0.0-dev.2) has stepped up the game too with a lot of new features.

You can find it here: https://rydmike.com/flexcolorscheme/themesplayground-v5

It is still included as "example 5" with the package as a tutorial, but it has now moved far beyond being a tutorial step for FlexColorScheme. 

I noticed that perhaps the usage of the AnimatedBuilder and single ChangeNotifier for all the properties that define ThemeData it creates, is maybe not ideal. (This is based on the Flutter skeleton template architecture). I think there may be a bit too many props (122 or so) listening to the ChangeNotifer and that this might slow things down a bit. Still all the props are basically things that if changed, then the entire app needs to rebuild since the theme changed, so from that point of view it is OK. It is not like, one would use a setup like this in a normal app, where you can't modify every little thing in the theme anyway. 

It all runs very well on device release build on tablets/phone, and of course also as desktop app build it is super fast and slick. However as a WEB build, even with CanvasKit only, it is not as smooth as I would like it to be.

Sure this app has quite complex layouts too. The big masonry grid view is still there, and there is a new page "topic" view with as well. Using NestedScrollview, custom sliver header delegates and other fancy Flutter stuff. Maybe that is causing it too. I have not even looked at optimizing it yet, I'm sure there are few things I can do to improve it. Even so it runs well enough for the intended purpose already on WEB too.

I will be releasing FlexColorScheme v5 as stable version when the docs are up to date, plus some minor tuning to the app as well, but that has nothing to do with the package.

![image](https://user-images.githubusercontent.com/39990307/161575307-bb03da2d-3f39-4b43-986f-c6176357fd16.png)

Going forward, I might do as with the docs for the Themes Playground app. Make it its own thing and repo so I can develop it independently of the package (like I can the docs now that they are their own site), and also move it away from the Flutter Skeleton architecture and set it up with Riverpod that I normally use. I wonder how many StateProvider's Remi recommends using in a single app, lol.

The way the persistence works for this app is that every little setting is its own key/value pair, with own setter/getter that persists it as needed using an abstract Theme service. So the implementation of it can be swapped out. It even is so as as a part of the tutorial too, Mem only, Share Prefs and Hive are used in the steps. Themes Playground uses Hive since it is faster than SharedPrefs.

It would certainly be less of a hassle to have a single data class for all the props and serialize them all, and persist them all just as one big JSON. However, with +100 props, I did not want to serialize/de-serialize the hole thing every time the user toggles a setting. I want it to be fast and storage resource efficient. So I thought it best that every setting is it own key/value pair. Saves on storage resource, and makes read/write much faster. 

Anyway, I'm rambling... thanks for the loader example. My own knowledge in that are are very limits so I just copied what you did, lol 😄

**Comment by rydmike** [comment]
Closing as done in new version 5 of the Themes Playground
