### ISSUE TITLE
In version 5 and 5.0.1, Persian characters are shown separately

### ISSUE THREAD

**Issue by mortezaejaz** [rydmike/flex_color_scheme#49]
![image](https://user-images.githubusercontent.com/20142130/166400708-cc171df7-5ecb-421d-b052-846179b630b7.png)

**Comment by rydmike** [comment]
Hi @mortezaejaz,

It is most likely because you opted in on using the optional Material3 text styles.
Does it help if you set `useTextTheme: false` ?

```dart
theme: FlexThemeData.light(
  scheme: FlexScheme.flutterDash,
  subThemesData: const FlexSubThemesData(
    useTextTheme: false,
  ),
),
darkTheme: FlexThemeData.dark(
  scheme: FlexScheme.flutterDash,
  subThemesData: const FlexSubThemesData(
    useTextTheme: false,
  ),
),
```

If it helps, please keep it turned off, for now. 

I'm suspecting this is the issue, because the FlexColorScheme internally used M3 TextTheme, when you opt-in on on using it (which it does by default when you enable opinionated sub-themes), does not offer correct geometry (Typography) for other languages than "English like" geometry using ones. Implementing support for this outside the framework itself is a bit difficult.

The "internal" and temporary `m3TextTheme` used now in FlexColorScheme https://pub.dev/documentation/flex_color_scheme/latest/flex_color_scheme/FlexColorScheme/m3TextTheme-constant.html will switch over to using the one built-in in Flutter framework, when it lands: https://github.com/flutter/flutter/pull/97829 in Flutter stable channel.

I'm hoping the full Typography support for Material 3 TextTheme will land in next stable version. After that I will release a new version that uses the Flutter Framework text theme instead. Hopefully that will resolve this issue. If it does not, then the issue will be in the Flutter framework.

If my guess is right we will get a new stable version of Flutter at Google I/O May 10-11, so hopefully quite soon, and I can apply a fix that you can try it then.

But first, try if it helps when you turn OFF the `useTextTeme`, when you do so it will just use the built in default TextTheme, or whatever TextTheme you provide.

Another thing came to mind as well, what font did you use above for the Persian characters?

**Comment by mortezaejaz** [comment]
Thank you for your help - useTextTheme: false, worked

**Comment by mortezaejaz** [comment]
Thanks for your guidance

**Comment by rydmike** [comment]
@mortezaejaz glad that it helped. I will drop a tagged notification here, when Typography has landed in Flutter and FlexColorScheme can and has been updated to use the built in theme that has correct Material Typography for Persian characters (and many Asian typography too). If you then have a chance to test and verify that it works with this flag kept true, that would be great.

I also added a note about this current and temporary limitation, to the docs [here](https://docs.flexcolorscheme.com/api_guide#flexsubthemesdata)
