### ISSUE TITLE
Differences preview in demoflexfold and flexcolorscheme -> backgroundColor completely white?

### ISSUE THREAD

**Issue by jlnrrg** [rydmike/flex_color_scheme#5]
Hey rydmike,
I noticed that colors in the main theme with especially light colors get outputted as white.
As an example lets take "backgroundColor", "canvasColor" and the Theme mandyRed.

On the [demoflexfold website](https://rydmike.com/demoflexfold/) -> Theme -> select Oh Mandy red theme the fields are slightly different than white (which is awesome), while in the [flexscheme demo](https://rydmike.com/flexcolorscheme1/#/) they are all listed as white.

As I personally like to use the slight white deviations, I wonder if that is an error or intentional and the demoflexfold shows wrong states.

**Comment by rydmike** [comment]
Hi @jlnrrg, 

I suspect what you are seeing is an effect of a subtle **implementation detail** in the Flexfold demo, and of course of **different** used **surface branding** in **example1** that uses "**none**" and "**medium**" that is used as default in the **Flexfold demo app**.

**Here are the details of what I think you are seeing**

First off, in **example1** in the bundle demos and live web example, that example **is not using any primary color surface branding** effects at all, so yes all surfaces in that example will always be **fully white** in light mode.

However, the Flexfold demo is using (can use) surface primary color branding, and by default it has the level set to "medium" here : 

![image](https://user-images.githubusercontent.com/39990307/106311125-4f84e980-626d-11eb-940b-560d60e0d8c1.png)

If you use example5 you can vary the same surface branding parameter API that Flexfold uses and set it to "medium" as well:

![image](https://user-images.githubusercontent.com/39990307/106311353-aee2f980-626d-11eb-93b0-af7c3e0de070.png)

Now you will get the same level of used primary color tint in **surface & card** color and in **background & canvas** color, the latter getting a bit stronger hint of it than than surface and card. Whereas scaffold background still has no surface branding at this strength. It only gets any color branding at the heavy strength.

![image](https://user-images.githubusercontent.com/39990307/106311535-fb2e3980-626d-11eb-8a60-334e4e603399.png)

If you color pick different widgets and surfaces with these settings you will find that they are identical in Flexfold Demo and Example 5:

![image](https://user-images.githubusercontent.com/39990307/106312222-033aa900-626f-11eb-865b-a0c2940fc674.png)

There is also a minor implementation detail in Flexfold, on the Settings and Theme pages, when you run it at "desktop" sizes, well the size where you have set it to use an expanded side menu in Settings, all the Settings switches and toggles, will get wrapped in extra Card, that by default will have the surface branding, and thus "Card color", since it is a card and just using default theme color.

If we set the the surface color branding to "heavy", the strongest one, it it will be even more visible than at medium (at medium there is only a hint of it). You can see it ibn the next screen shot. It is using the surface & card color, since the controls are in this layout size in an extra Card wrapper, this is just an implementation detail I did for the Flexfold demo:

![image](https://user-images.githubusercontent.com/39990307/106313063-46e1e280-6270-11eb-968b-9d70e019f034.png)

When you go down in size to typical tablet width or even phone width, that extra desktop/web size only wrapper is removed:

![image](https://user-images.githubusercontent.com/39990307/106313235-8c9eab00-6270-11eb-95b8-b1de15d13606.png) 

Just for a more compact layout and because it did not looks so nice on mobile with that extra color there color:

![image](https://user-images.githubusercontent.com/39990307/106313277-9aecc700-6270-11eb-8785-f423d728c0e1.png)

Since we were now in "heavy" branding mode, the scaffold background also actually has a hint of primary color, but only a really small amount, but all the other surface colors are pretty heavily surface branded at this point:

![image](https://user-images.githubusercontent.com/39990307/106313534-0d5da700-6271-11eb-9998-3d0cf5bb1ab2.png)

When you go to "strong" then the scaffold background is fully white again, whereas other surface colors are still quite strongly primary color branded:

![image](https://user-images.githubusercontent.com/39990307/106313707-4a299e00-6271-11eb-92e9-43eddd2d1059.png)

As you step down in surface color branding all the way to default material surfaces, all surfaces become fully white in light mode:

![image](https://user-images.githubusercontent.com/39990307/106313859-8b21b280-6271-11eb-9ddd-01d5627db015.png)

The example 1 you compared to uses that setting.

---

You can experiment with the surface branding API setting and vary the strength of it to a level that fits your use case and design, or not use it at all. 

It is easy to and see the impact of it eg with example 5, you of course don't have to provide any toggle or setting for it in app, the API is just intended to help you find a level that fits your design and stick to it. Most users would probably get super confused if you present them with as many theming options as FlexColorScheme Example5 or Flexfold demo provides. 😃  

The appropriate level of surface branding varies a bit depending on the saturation of used primary color, and personal taste of course. So hence four different levels is provided, well five with none.
It also varies between light/dark mode and you can of course use different surface color branding strength in the light and dark theme if you want to.

Although the level between dark/light mode has been tuned so that they kind of provide the same level of primary color branding intensity at same setting. To do so the dark mode equivalent color branding levels blend in much more of the primary color for same perceived visual impact, typically almost double the amount.

---

Hope this answers you question :)

-Mike

**Comment by jlnrrg** [comment]
Thank you again for this really extensive explanation.
And I have to admit, I feel stupid now, have I found the entry to [example5](https://github.com/rydmike/flex_color_scheme/blob/master/example/lib/example5/main.dart) in your documentation, after you helped me understand surface branding.

At this point I like to provoke the thought to provide a more simplified setup guide with less prose text additionally.
While as an developer I enjoy really well documented librarys (and you are for sure in the top here), 
I often find myself reading through it earliest at specific use cases and for the rest just following simple setup guides.

I have yet to come up with an idea how that would look for a package like flex_color_scheme myself, but I have a documentation in mind like [freezed](https://pub.dev/packages/freezed#how-to-use).

**Comment by jlnrrg** [comment]
At this point I just want to add, that the `blend()` method comes in really handy to create a scaffoldBackgroundColor (or any other for that matter) based on existing Theme Colors. Great work :smile:.

```dart

static FlexScheme usedFlexScheme = FlexScheme.aquaBlue;
static FlexSurface flexSurface = FlexSurface.light;

static ThemeData lightTheme(BuildContext context) {
    final ThemeData baseTheme = FlexColorScheme.light(
      scheme: usedFlexScheme,
      surfaceStyle: flexSurface,
    ).toTheme;
    return baseTheme.copyWith(
        visualDensity: FlexColorScheme.comfortablePlatformDensity,
        textTheme: GoogleFonts.firaSansTextTheme(baseTheme.textTheme),
        scaffoldBackgroundColor:
            Colors.white.blend(baseTheme.primaryColorLight)); // <- here
  }
```

**Comment by rydmike** [comment]
Glad you like it 😃 
And yes I use it myself like this too when you want to do some more custom blending.

The automatic dark theme also uses blend to create more desaturated "white blended" colors of all its light scheme colors.

I thought about having more convenience surface styles, but I figured since all the tools to make custom/advanced schemes and themes are exposed, that if anybody wants something more custom you can do exactly like you did.

By the way, every FlexColorScheme API is fully documented:
https://pub.dev/documentation/flex_color_scheme/latest/flex_color_scheme/flex_color_scheme-library.html
Some typos here and there still. Improving them now and then when I notice stuff. Feel free to send correction and enhancement proposals.

For example the **blend** API extension is here: https://pub.dev/documentation/flex_color_scheme/latest/flex_color_scheme/FlexColorExtensions/blend.html

It also takes an optional blend strength. What you get in your example is default 10% blend, when using just blend(color), but that is probably what you wanted in this case. It should work well when using `primaryColorLight` as base. Otherwise 10% is quite a heavy blend value for a light background, at least when basing it off primary color that usually has much higher color saturation.

A similar result as the one with the `primaryColorLight`, could eg be gotten by using:

`Colors.white.blend(baseTheme.colorScheme.primary, 5));`

Well roughly anyway, not sure what `blend` value with `colorScheme.primary` gives exactly the same end color, but you get the idea.

I'm just saying this because I fully expect Google to deprecate and remove `primaryColor`, `primaryColorLight` and `primaryColorDark` some day from `ThemeData`, probably not very soon though. However, according to the plan (link to it exists in the package docs somewhere) they mention that it is their intention.

Those properties are old `ThemeData` color properties. In particular  `primaryColorLight` and `primaryColorDark` that no longer even get any values in Flutter's own `ColorScheme` based themes. FlexColorScheme gives them values to ensure they match the color scheme's primary color. With Flutter's own `ColorScheme` based theming they remain at light and dark blue, stupid really.

Since this is the case, and they won't fix it and due to the transition plan, I'm fully expecting those color properties to go away in some near Flutter version updates. FlexColorScheme will then of course have to follow suite and remove them too.

When this happens, it is of course a pity that Flutter then no longer offer's any ThemeData colors that would be guaranteed to be of different shades of the primary color.

Due to all this I recommend theming all custom widgets to use default colors based on Theme.of(context).colorScheme colors, and if needed expose their color properties as well to override without a theme. This is what the SDK does as well, or all new stuff anyway, a few older widgets still use color properties from ThemeData directly and not from ThemeData.colorScheme.

In FlexColorScheme there are also some other convenience color extension and static methods that can help with that different hue and saturation of a given color, for example:

```dart
Color myColor1 = Theme.of(context).colorScheme.primary.lighten(value);
Color myColor2 = Theme.of(context).colorScheme.primary.brighten(value);
Color myColor3 = Theme.of(context).colorScheme.primary.darken(value);
```
where value is int 0 ... 100 %

And you can also e.g. do this:

`MaterialColor colorSwatch = FlexColorScheme.createPrimarySwatch(Theme.of(context).colorScheme.primary);`

Then you get a MaterialColor like color swatch where colorSwatch[500] is the the same as the provided color value and the lower
indexes are lighter saturation and higher are darker, just as in the default built in MaterialColor swatches.

If the Color passed to it is actually the same color as real Material color index 500, the return swatch will however **not** be the same as the real Material swatch the 500 index color is a part of.

----

**FlexColorPicker** includes a tool that can do that as well, with its `ColorTools` you can do this:

`MaterialColor colorSwatch = ColorTools.primarySwatch(anyColor);`

If the color passed to it is found in any of the standard MaterialColor swatches in any index value, then the actual MaterialColor Swatch the color is a part of is returned, and you can then get access to all its actual color swatch values.

If that color is not found in any built in MaterialColor swatch, then the same above `createPrimarySwatch` is automatically called, using the provided color as the 500 index to create a swatch and return it instead, so you still get a swatch then as well.

This feature is used by the **FlexColorPicker** to find in which picker type a color value exists of the enabled color picker types, so it can display the selected color with the most optimal picker when you provide it a starting color (or copy paste color values to it).

I've been thinking of bringing this little `primarySwatch` tool also as a static method on FlexColorScheme. I would like to use it for those automatic scheme's based on single primary color or primary + secondary color, so that when you give a primary or secondary color that is actually a real MaterialColor swatch color in any index, it would find its swatch and base the derived color values of colors in that swatch and use them for variant colors and also the light and dark primary colors. 

Now it just computes lighter and darker values and a creates a primary swatch to pic two index values out of it for the light and dark colors. They are however not shades from the real MaterialColor color swatch, if the provided starting point was such a color. I would like to enable a feature that makes it possible to have them use real MaterialColor swatch colors as well / instead if the provided base color is such a color in MaterialColor index.

Obviously current default behavior would remain as is, but this behavior could be used instead.
