### ISSUE TITLE
appbar center title not found

### ISSUE THREAD

**Issue by mstfkhazaal** [rydmike/flex_color_scheme#59]

**Comment by rydmike** [comment]
@mstfkhazaal I'm going to need a bit more explanation than that to know for sure what the issue is.

* Some kind of error?
* Feature request?

As stated in the docs, **FlexColorScheme** does not offer every theming property that is available in the SDK. It does not attempt to be a complete rewrite for everything Flutter theming already does well. It adds convenience features for things that are tricky or quite hard to do.

FlexColorScheme just creates standard `Themedata` object and you can create a copy of it with additional things in changed by using `copyWith` just as with `ThemeData´, it is in fact the returned `ThemeData` that you do the `copyWith` on.

See more info here: https://docs.flexcolorscheme.com/faq#how-do-i-modify-the-component-themes-with-custom-features

So if you want to define a theme where `AppBar` title is always centered (it is centered by default on iOS/MacOs, but not on other platforms), then the same principle as in the example can be used.

Only a heading as issue report is bit too terse for me to be sure I understand what you mean, but this was a best guess.

**Comment by mstfkhazaal** [comment]
Thanks

**Comment by rydmike** [comment]
I might add this property in a future version though, it is a pretty popular one to use so it would often be handy to have it included without the need for a copyWith.

**Comment by rydmike** [comment]
Just as heads up, I did add this, not released yet, but it will be included when I release next version.

**Comment by rydmike** [comment]
Feature exists in version 6.0.0
https://pub.dev/documentation/flex_color_scheme/latest/flex_color_scheme/FlexSubThemesData/appBarCenterTitle.html
