### ISSUE TITLE
Option to add fontFamilyFallback

### ISSUE THREAD

**Issue by rddewan** [rydmike/flex_color_scheme#93]
Hi,
Is there a way to add `fontFamilyFallback` directly to the FlexThemeData or any way to do it directly in them.

Thank you

**Comment by rydmike** [comment]
Hi @rddewan,

## Using `fontFamilyFallback` in FlexColorScheme

Yes you can.

Since `fontFamilyFallback` is a property in `TextStyle`, and all Material standard styles are a part of `TextTheme`, that is a part of `ThemeData`. And since `FlexColorScheme` also has a direct `textTheme` (and `primaryTextTheme`) property, then yes you can. You can even do it without `copyWith` on the `FlexThemeData` or `FlexColorScheme.toTheme` produced `ThemeData`.

You do it exactly as you would define `fontFamilyFallback` for standard `ThemeData`. Specify it as a part of each customized `TextStyle` that you include in your custom `TextTheme`, and then assign this to `textTheme` property in `FlexColorScheme` or the alternate convenience constructor `FlexThemeData`.

So yes it is possible, but there are no additional convenience features around adding it. If you are making fully defined custom text styles and giving them via `textTheme`, then defining `fontFamilyFallback` in the custom styles at the same time makes works well. However... 

## New feature idea: Add `fontFamilyFallback` property for convenience

Looking at this another way. Say you just want a custom font for all text styles in the default `TextTheme`, and you are using `fontFamily` for that. I can then agree that it would be very convenient if there was an equivalent `fontFamilyFallback` property where you could add a fallback list that is added to all default text styles. It could even do so to the custom `TextTheme` you provide, as another way of setting it, instead of the style defs in `TextTheme`.

I will add this as a potential new feature to look into. It would be a nice convenience feature to have, just like "fontFamily" is today in `ThemeData`. It could even be simple config class that we add and we could optionally define different fallback lists for different target platforms, since they often have different fallback fonts.

For now though, the way to do it is via the same longer a bit tedious way that you also do with normal `ThemeData`.

Not sure if doing just as with `ThemeData` is what you were looking for, or if you were asking  for a `fontFamilyFallback` convenience feature. Even if not, I can see how it could be useful.

## Related topic: `fontFamily` deprecation in `ThemeData`

By the way, it looks like `fontFamily` convenience property is going to go away from `ThemeData` in some future Flutter SDK version. 

Even if it does I will probably continue to support it in `FlexColorScheme`, among with maybe even adding the `fontFamilyFallback` convenience. 

See here for info that `fontFamily` is on the `ThemeData` deprecation list:

https://github.com/flutter/flutter/issues/91772


![Screen Shot 2022-10-21 at 20 34 25](https://user-images.githubusercontent.com/39990307/197255480-0c0d3e32-ef1c-41e8-a982-4a0428971bdb.png)

**Comment by rddewan** [comment]
thank you

**Comment by rydmike** [comment]
@rddewan I made a comment in https://github.com/flutter/flutter/issues/91772 about deprecation of `fontFamily`, which is a bit at odds with this PR tat actually adds `fontFamilyFallback ` to `ThemeData`. You can find min comment here https://github.com/flutter/flutter/issues/91772#issuecomment-1292452647

Be the result and faith of `fontFamily` and `fontFamilyFallback` as direct properties in `ThemeData` I will keep `fontFamily` in FlexColorScheme and also add `fontFamilyFallback` to it.

Implementing support for `fontFamilyFallback` got a lot easier thanks to PR https://github.com/flutter/flutter/pull/112976 that also included `TextTheme.apply(fontFamilyFallback)` that was missing before, I would have had to also implement what it does to apply it to the `textTheme` and `primaryTextTheme`, now I can just use.

These `fontFamilyFallback` feature will be added to FlexColorScheme after PR https://github.com/flutter/flutter/pull/112976 lands in Flutter stable release. Which might be version 3.6 in maybe 1-2 months. Just a guess, I have now info on when next version will be released and when and what the version number will be.

**Comment by rddewan** [comment]
@rydmike  great to hear about it , thank you @

**Comment by rydmike** [comment]
@rddewan no problem, you might have noticed that after I made my comment about the a bit conflicting deprecation strategy of deprecating `fontFamily` but adding `fontFamilyFallback`, that the plan to deprecate `fontFamily` was reverted, so it will stay in `ThemeData` going forward too. See here https://github.com/flutter/flutter/issues/91772#issuecomment-1293982017

**Comment by rydmike** [comment]
This feature will be included in the next FlexColorScheme feature release, currently the WIP release version number is 6.2.0 since it contains no breaking changes so far, even if the release will be quite major feature wise.

Target is to release it shortly (few days) after the Flutter Forward event on Jan 25th, 2023.

**Comment by rydmike** [comment]
Still same milestone target, but the release will be called 7.0.0, since I am introducing a few minor default style breaking changes. There are no breaking API changes though. There is a beta of it available on pub if you are feeling experimental, it includes this new property. 
https://pub.dev/packages/flex_color_scheme/versions/7.0.0-dev.2

**Comment by rydmike** [comment]
Final beta of version 7 is out. There will be no additional features or API changes in the stable release. More info in this tweet thread: 

https://twitter.com/RydMike/status/1637228788139302914?s=20

Closing this feature request as delivered in version7 final beta 😄
